SolidTech.Presentation/Areas/Admin/Controllers/MySolutionController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata;

namespace SolidTech.Presentation.Areas.Admin.Controllers
{
    [Authorize]
    [Area("Admin")]
    public class MySolutionController : Controller
    {

        ISolutionService _solutionService;

        public MySolutionController(ISolutionService solutionService)
        {
           _solutionService = solutionService;           
        }


        public IActionResult Index()
        {

            var solutions = _solutionService.GetServices();
            return View(solutions);

        }


        [HttpGet] 
        public IActionResult AddNewSolutionPage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddNewSolution(SolutionDto solutionDto)
        {

            if (!ModelState.IsValid)
            {
                return View("AddNewSolutionPage", solutionDto);
            }

            

            _solutionService.AddSolution(solutionDto);


            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult DeleteSolution(int id)
        {


            return RedirectToAction("Index");
        }


        [HttpGet]
        public IActionResult EditSolutionPage(int id)
        {
            var result = _solutionService.GetSolutionById(id);

            if (result != null)
            {
                return View(result);
            }

            ViewBag.ErrorMessage = "Nesne null";

            return RedirectToAction("Index");

        }




    }
}

SolidTech.Presentation/Areas/Admin/Views/MySolution/AddNewSolutionPage.cshtml
@model SolidTech.Business.Dtos.SolutionDto

@{
    ViewData["Title"] = "AddNewSolutionPage";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<h1>MERHABA BURASI HİZMET EKLEME SAYFASI</h1>

<div class="container" style="width:30%">
    @using (Html.BeginForm("AddNewSolution","MySolution",new {area="Admin"},FormMethod.Post,null,new { @class ="form"  }))
    {

        <div class="input-group mb-3">
            <span class="input-group-text">Service Name</span>
            @Html.TextBoxFor(s=>s.Header,new {@class="form-control" ,placeholder="Service Name"})
            @Html.ValidationMessageFor(s=>s.Header,"",new {@class = "text-danger"})


        </div>

        <div class="input-group mb-3">
            <span class="input-group-text">Service Content</span>
            @Html.TextBoxFor(s => s.Content, new { @class = "form-control", placeholder = "Service Name" })
            @Html.ValidationMessageFor(s => s.Content, "", new { @class = "text-danger" })

        </div>

        <div class="input-group mb-3">
            <span class="input-group-text">Service ImageIcon</span>
            @Html.TextBoxFor(s => s.ImageIcon, new { @class = "form-control", placeholder = "Service Name" })
            @Html.ValidationMessageFor(s => s.ImageIcon, "", new { @class = "text-danger" })
        </div>
        <div style="display:flex;justify-content:flex-end;width:100%;">
            <button class="btn btn-success" type="submit">Servis EKLE</button>
        </div>

    }



</div>

SolidTech.Presentation/Areas/Admin/Views/MySolution/EditSolutionPage.cshtml
@model SolidTech.Data.Entities.Solution

@{
    ViewData["Title"] = "EditSolutionPage";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<h1>MERHABA BURASI HİZMET EKLEME SAYFASI</h1>

<div class="container" style="width:30%">
    <form action="/Admin/MySolution/AddNewSolution" method="post">
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">Service Name</span>
            <input type="text" class="form-control" aria-label="Username" aria-describedby="basic-addon1" name="Header" value=@Model.Header>
        </div>
        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">Content</span>
            <input type="text" class="form-control" aria-label="Username" aria-describedby="basic-addon1" name="Content" value=@Model.Content>
        </div>

        <div class="input-group mb-3">
            <span class="input-group-text" id="basic-addon1">Image Icon URL</span>
            <input type="text" class="form-control" aria-label="Username" aria-describedby="basic-addon1" name="ImageIcon" value=@Model.CreaDate.ToString("dd/MM/yyyy") disabled>
        </div>

        <div style="display:flex;justify-content:flex-end;width:100%;">
            <button class="btn btn-success" type="submit">HİZMET EKLE</button>
        </div>

    </form>

</div>

SolidTech.Presentation/Areas/Admin/Views/MySolution/Index.cshtml
@model List<SolutionDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="container">
    <h1>MERHABA BURASI HİZMETLERİMİZİN OLDUĞU SAYFA</h1>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Header</th>
                <th scope="col">Content</th>               
                <th scope="col"></th>
                <th scope="col">
                    <a href="@Url.RouteUrl("admin_default",new {controller="MySolution",action="AddNewSolutionPage"})" class="nav-link">
                        <i class="fa-solid fa-circle-plus"></i>
                        Add New Solution
                    </a>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var solution in Model)
            {
                <tr>
                    <th scope="row">@solution.SolutionId</th>
                    <td>@solution.Header</td>
                    <td>@solution.Content</td>
                    <td>
                        <a href="@Url.RouteUrl("admin_default",new {controller="MySolution",action="EditSolutionPage",id=solution.SolutionId})" class="btn btn-success">EDİT</a>
                    </td>
                    <td>
                        <a href="/Admin/MySolution/DeleteSolution/@solution.SolutionId" class="btn btn-danger">DELETE</a>
                    </td>
                </tr>
            }


        </tbody>
    </table>

</div>