SolidTech.Presentation/Areas/Admin/Components/MailPartViewComponent.cs
namespace SolidTech.Presentation.Areas.Admin.Components
{
    public class MailPartViewComponent:ViewComponent
    {
        IMessageService _messageService;
   

        public MailPartViewComponent(IMessageService messageService)
        {
            _messageService = messageService;
          
        }

        public IViewComponentResult Invoke(string messageType="inbox")
        {

            List<MessageDto> messages;
           

            if (messageType == "inbox")
            {
                messages = _messageService.GetMessagesByTypeId(1);
            }
            else
            {
                messages = _messageService.GetMessagesByTypeId(2);
            }
            

            return View(messages);
        }




    }
}

SolidTech.Presentation/Areas/Admin/Controllers/MyMessageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SolidTech.Presentation.Areas.Admin.Controllers
{

    [Authorize(Roles ="Admin")]
    [Area("Admin")]
    public class MyMessageController : Controller
    {
        IMessageService _messageService;
     
        public MyMessageController(IMessageService messageService)
        {
            _messageService = messageService;
  
        }


       
        public IActionResult Index(string messageType = "inbox")
        {

            ViewBag.MessageType = messageType;

            var MessageList = _messageService.Messages();

            return View(MessageList);
        }


        [HttpGet]
        public IActionResult ViewMessageDetail(int message_id)
        {

            var message = _messageService.GetMessageById(message_id);

            if (message != null)
            {
                return View(message);
            }


            return RedirectToAction("Index");

        }





    }
}

SolidTech.Presentation/Areas/Admin/Views/MyMessage/Index.cshtml
@using SolidTech.Business.Dtos

@model List<MessageDto>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    string messageType = ViewBag.MessageType;
}

<section class="content">
    <div class="row">
        <div class="col-md-3">
            <a href="compose.html" class="btn btn-primary btn-block mb-3">Compose</a>

            <div class="card">
                <div class="card-header">
                    <h3 class="card-title">Folders</h3>

                    <div class="card-tools">
                        <button type="button" class="btn btn-tool" data-card-widget="collapse">
                            <i class="fas fa-minus"></i>
                        </button>
                    </div>
                </div>
                <div class="card-body p-0">
                    <ul class="nav nav-pills flex-column">
                        <li class="nav-item active">
                            <a href="?messageType=inbox" class="nav-link">
                                <i class="fas fa-inbox"></i> Inbox
                                <span class="badge bg-primary float-right">12</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="?messageType=sent" class="nav-link">
                                <i class="far fa-envelope"></i> Sent
                            </a>
                        </li>

                    </ul>
                </div>

            </div>

        </div>
  
        <div class="col-md-9">
            @await Component.InvokeAsync("MailPart", messageType)
        </div>
    </div>
</section>

SolidTech.Presentation/Areas/Admin/Views/MyMessage/ViewMessageDetail.cshtml
@using SolidTech.Data.Entities
@model Message

@{
    ViewData["Title"] = "ViewMessageDetail";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <a href="@Url.RouteUrl("admin_default", new { controller = "MyMessage", action = "Index" })" class="btn btn-primary btn-block mb-3">Back to Inbox</a>

                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Folders</h3>

                        <div class="card-tools">
                            <button type="button" class="btn btn-tool" data-card-widget="collapse">
                                <i class="fas fa-minus"></i>
                            </button>
                        </div>
                    </div>
                    <div class="card-body p-0">
                        <ul class="nav nav-pills flex-column">
                            <li class="nav-item">
                                <a href="@Url.RouteUrl("admin_default", new { controller = "MyMessage", action = "Index", messageType = "inbox" })" class="nav-link">
                                    <i class="fas fa-inbox"></i> Inbox
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.RouteUrl("admin_default", new { controller = "MyMessage", action = "Index", messageType = "sent" })" class="nav-link">
                                    <i class="far fa-envelope"></i> Sent
                                </a>
                            </li>
                                              
                        </ul>
                    </div>
                    <!-- /.card-body -->
          </div>
            
            </div>
            <!-- /.col -->
            <div class="col-md-9">
                <div class="card card-primary card-outline">
                    <div class="card-header">
                        <h3 class="card-title">Read Mail</h3>

                        <div class="card-tools">
                            <a href="#" class="btn btn-tool" title="Previous"><i class="fas fa-chevron-left"></i></a>
                            <a href="#" class="btn btn-tool" title="Next"><i class="fas fa-chevron-right"></i></a>
                        </div>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-0">
                        <div class="mailbox-read-info">
                            <h5>@Model.MessageHeader</h5>
                            <h6>
                                From: @Model.Email
                                <span class="mailbox-read-time float-right">15 Feb. 2015 11:03 PM</span>
                            </h6>
                        </div>
                        <!-- /.mailbox-read-info -->
                        <div class="mailbox-controls with-border text-center">
                           
                            <!-- /.btn-group -->
                       
                        </div>
                        <!-- /.mailbox-controls -->
                        <div class="mailbox-read-message">
                      
                            <p>
                               @Model.MessageContent
                            </p>

                            <div class="btn-group">
                                <button type="button" class="btn btn-default btn-sm" data-container="body" title="Delete">
                                    <i class="far fa-trash-alt"></i>
                                </button>
                                <button type="button" class="btn btn-default btn-sm" data-container="body" title="Reply">
                                    <i class="fas fa-reply"></i>
                                </button>
                                <button type="button" class="btn btn-default btn-sm" data-container="body" title="Forward">
                                    <i class="fas fa-share"></i>
                                </button>
                                <button type="button" class="btn btn-default btn-sm" title="Print">
                                    <i class="fas fa-print"></i>
                                </button>
                            </div>
                        </div>
                        <!-- /.mailbox-read-message -->
                    </div>
                    <!-- /.card-body -->
                
                            </li>
                        </ul>
                    </div>
               
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>

SolidTech.Presentation/Areas/Admin/Views/MyMessage/ViewSendingMessages.cshtml
@{
    ViewData["Title"] = "ViewSendingMessages";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>ViewSendingMessages</h1>